/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import edu.QLCH.Dao.NhanVienDao;
import edu.QLCH.Entity.NhanVien;
import edu.QLCH.Helper.AuthHelper;
import edu.QLCH.Helper.MsgBoxHelper;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author ASUS
 */
public class MainFormJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFormJFrame1
     */
    public MainFormJFrame() {
        initComponents();
        init();
        vaitro();
        checklogin();
        
    }
 NhanVienDao nvdao = new NhanVienDao();
    void init(){
            setLocationRelativeTo(null);
            setTitle("HỆ THỐNG QUẢN LÝ CỬA HÀNG");
            new Timer(1000, new ActionListener() {
            SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss a");

            @Override
            public void actionPerformed(ActionEvent e) {
                jLabel2.setText(sdf.format(new Date()));
            }
        }).start();
            showChao();
            Login();
    }
     void vaitro(){
        lblUser.setText(String.valueOf(AuthHelper.user.getHoTen()));
        lblChucVu.setText(String.valueOf(AuthHelper.user.isVaiTro()?"Trưởng phòng":"Nhân viên"));
    }   
    public void checklogin(){
        
        if(!AuthHelper.user.isVaiTro()){
             pnlthongke.setVisible(false);
             pnlNhanvien.setVisible(false);
        } else {
            pnlthongke.setVisible(true);
        }
   
    }
    public void showChao() {
        new ChaoKHJDialog(this,true).setVisible(true);
    }
    public void Login(){
        new DangNhapJDialog(this,true).setVisible(true);
    }
    
    public void OpenNhanVien(){
        new QuanLyNhanVienJDialog(this,true).setVisible(true);
    }
    public void OpenKhachHang(){
        new QuanLyKhachHangJDialog(this,true).setVisible(true);
    }
     public void OpenSanPham(){
        new QuanLySanPhamJDialog(this,true).setVisible(true);
    }
    public void OpenThongKe(){
        new ThongkeJDialog(this,true).setVisible(true);
        
    }
     public void OpenLoaiSP(){
        new QuanLyLoaiSPJDialog(this,true).setVisible(true);
    }
      public void OpenHoaDon(){
        new QuanLyHD(this,true).setVisible(true);
    }
     public void OpenDMK(){
        new DoimatkhauJdialog(this,true).setVisible(true);
    }
      void dangXuat(){
        AuthHelper.clear();
        MsgBoxHelper.alert(this, "Đăng Xuất thành công");
        new DangNhapJDialog(this, true).setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        lblChucVu = new javax.swing.JLabel();
        pnlTrangChu = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        pnlKH = new javax.swing.JPanel();
        btnKhachhang = new javax.swing.JButton();
        pnlThanhtoan = new javax.swing.JPanel();
        btnThanhtoan = new javax.swing.JButton();
        pnlthongke = new javax.swing.JPanel();
        btnthongke = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        btnSetting = new javax.swing.JButton();
        btnAccount = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        pnlsp = new javax.swing.JPanel();
        btnSanpham = new javax.swing.JButton();
        pnlSanpham1 = new javax.swing.JPanel();
        btnSanpham1 = new javax.swing.JButton();
        pnlNhanvien = new javax.swing.JPanel();
        btnNhanvien = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pnlContent = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setBackground(new java.awt.Color(55, 38, 91));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        lblUser.setText("Lê Minh Trường");
        lblUser.setMaximumSize(new java.awt.Dimension(157, 50));
        lblUser.setMinimumSize(new java.awt.Dimension(157, 50));
        lblUser.setPreferredSize(new java.awt.Dimension(157, 50));
        pnlMenu.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 24, 190, -1));

        lblChucVu.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblChucVu.setForeground(new java.awt.Color(255, 255, 255));
        lblChucVu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblChucVu.setText("TRƯỞNG PHÒNG");
        pnlMenu.add(lblChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 100, 100));

        pnlTrangChu.setBackground(new java.awt.Color(55, 38, 91));
        pnlTrangChu.setPreferredSize(new java.awt.Dimension(220, 47));

        btnHome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        btnHome.setText("Trang chủ");
        btnHome.setBorder(null);
        btnHome.setBorderPainted(false);
        btnHome.setContentAreaFilled(false);
        btnHome.setDefaultCapable(false);
        btnHome.setFocusPainted(false);
        btnHome.setFocusable(false);
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHome.setIconTextGap(25);
        btnHome.setMaximumSize(new java.awt.Dimension(124, 25));
        btnHome.setMinimumSize(new java.awt.Dimension(124, 25));
        btnHome.setPreferredSize(new java.awt.Dimension(124, 25));

        javax.swing.GroupLayout pnlTrangChuLayout = new javax.swing.GroupLayout(pnlTrangChu);
        pnlTrangChu.setLayout(pnlTrangChuLayout);
        pnlTrangChuLayout.setHorizontalGroup(
            pnlTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTrangChuLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlTrangChuLayout.setVerticalGroup(
            pnlTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTrangChuLayout.createSequentialGroup()
                .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pnlMenu.add(pnlTrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 186, 230, -1));

        pnlKH.setBackground(new java.awt.Color(55, 38, 91));
        pnlKH.setPreferredSize(new java.awt.Dimension(221, 47));

        btnKhachhang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnKhachhang.setForeground(new java.awt.Color(255, 255, 255));
        btnKhachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/khachHang.png"))); // NOI18N
        btnKhachhang.setText("Quản lý khách hàng");
        btnKhachhang.setToolTipText("");
        btnKhachhang.setBorder(null);
        btnKhachhang.setBorderPainted(false);
        btnKhachhang.setContentAreaFilled(false);
        btnKhachhang.setDefaultCapable(false);
        btnKhachhang.setFocusPainted(false);
        btnKhachhang.setFocusable(false);
        btnKhachhang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnKhachhang.setIconTextGap(25);
        btnKhachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachhangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlKHLayout = new javax.swing.GroupLayout(pnlKH);
        pnlKH.setLayout(pnlKHLayout);
        pnlKHLayout.setHorizontalGroup(
            pnlKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKHLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(btnKhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlKHLayout.setVerticalGroup(
            pnlKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKHLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKhachhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlMenu.add(pnlKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 244, 230, -1));

        pnlThanhtoan.setBackground(new java.awt.Color(55, 38, 91));
        pnlThanhtoan.setPreferredSize(new java.awt.Dimension(221, 47));

        btnThanhtoan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThanhtoan.setForeground(new java.awt.Color(255, 255, 255));
        btnThanhtoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/money.png"))); // NOI18N
        btnThanhtoan.setText("Quản lý hóa đơn");
        btnThanhtoan.setBorder(null);
        btnThanhtoan.setBorderPainted(false);
        btnThanhtoan.setContentAreaFilled(false);
        btnThanhtoan.setDefaultCapable(false);
        btnThanhtoan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnThanhtoan.setIconTextGap(25);
        btnThanhtoan.setMaximumSize(new java.awt.Dimension(133, 25));
        btnThanhtoan.setMinimumSize(new java.awt.Dimension(133, 25));
        btnThanhtoan.setPreferredSize(new java.awt.Dimension(133, 25));
        btnThanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhtoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlThanhtoanLayout = new javax.swing.GroupLayout(pnlThanhtoan);
        pnlThanhtoan.setLayout(pnlThanhtoanLayout);
        pnlThanhtoanLayout.setHorizontalGroup(
            pnlThanhtoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThanhtoanLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(btnThanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlThanhtoanLayout.setVerticalGroup(
            pnlThanhtoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThanhtoanLayout.createSequentialGroup()
                .addComponent(btnThanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlMenu.add(pnlThanhtoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 230, -1));

        pnlthongke.setBackground(new java.awt.Color(55, 38, 91));
        pnlthongke.setPreferredSize(new java.awt.Dimension(220, 47));

        btnthongke.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnthongke.setForeground(new java.awt.Color(255, 255, 255));
        btnthongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plan.png"))); // NOI18N
        btnthongke.setText("Quản lý thống kê");
        btnthongke.setToolTipText("");
        btnthongke.setAutoscrolls(true);
        btnthongke.setBorder(null);
        btnthongke.setBorderPainted(false);
        btnthongke.setContentAreaFilled(false);
        btnthongke.setDefaultCapable(false);
        btnthongke.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnthongke.setIconTextGap(25);
        btnthongke.setMaximumSize(new java.awt.Dimension(119, 25));
        btnthongke.setMinimumSize(new java.awt.Dimension(119, 25));
        btnthongke.setPreferredSize(new java.awt.Dimension(119, 25));
        btnthongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthongkeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlthongkeLayout = new javax.swing.GroupLayout(pnlthongke);
        pnlthongke.setLayout(pnlthongkeLayout);
        pnlthongkeLayout.setHorizontalGroup(
            pnlthongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlthongkeLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(btnthongke, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlthongkeLayout.setVerticalGroup(
            pnlthongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlthongkeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnthongke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );

        pnlMenu.add(pnlthongke, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 230, -1));

        jPanel12.setBackground(new java.awt.Color(83, 62, 128));
        jPanel12.setToolTipText("");
        jPanel12.setPreferredSize(new java.awt.Dimension(116, 42));

        btnSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/setting.png"))); // NOI18N
        btnSetting.setBorder(null);
        btnSetting.setBorderPainted(false);
        btnSetting.setContentAreaFilled(false);
        btnSetting.setDefaultCapable(false);
        btnSetting.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/group.png"))); // NOI18N
        btnAccount.setBorder(null);
        btnAccount.setBorderPainted(false);
        btnAccount.setContentAreaFilled(false);
        btnAccount.setDefaultCapable(false);
        btnAccount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountActionPerformed(evt);
            }
        });

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        btnLogout.setBorder(null);
        btnLogout.setBorderPainted(false);
        btnLogout.setContentAreaFilled(false);
        btnLogout.setDefaultCapable(false);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSetting)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAccount)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSetting, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAccount, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenu.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 758, 230, -1));

        pnlsp.setBackground(new java.awt.Color(55, 38, 91));
        pnlsp.setPreferredSize(new java.awt.Dimension(220, 47));

        btnSanpham.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSanpham.setForeground(new java.awt.Color(255, 255, 255));
        btnSanpham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticket.png"))); // NOI18N
        btnSanpham.setText("Quản lý loại sản phẩm");
        btnSanpham.setBorder(null);
        btnSanpham.setBorderPainted(false);
        btnSanpham.setContentAreaFilled(false);
        btnSanpham.setDefaultCapable(false);
        btnSanpham.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSanpham.setIconTextGap(25);
        btnSanpham.setMaximumSize(new java.awt.Dimension(175, 20));
        btnSanpham.setMinimumSize(new java.awt.Dimension(175, 20));
        btnSanpham.setPreferredSize(new java.awt.Dimension(175, 20));
        btnSanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanphamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlspLayout = new javax.swing.GroupLayout(pnlsp);
        pnlsp.setLayout(pnlspLayout);
        pnlspLayout.setHorizontalGroup(
            pnlspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlspLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnSanpham, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlspLayout.setVerticalGroup(
            pnlspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlspLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSanpham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(64, 64, 64))
        );

        pnlMenu.add(pnlsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 230, -1));

        pnlSanpham1.setBackground(new java.awt.Color(55, 38, 91));
        pnlSanpham1.setPreferredSize(new java.awt.Dimension(221, 47));

        btnSanpham1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSanpham1.setForeground(new java.awt.Color(255, 255, 255));
        btnSanpham1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticket.png"))); // NOI18N
        btnSanpham1.setText("Quản lý sản phẩm");
        btnSanpham1.setBorder(null);
        btnSanpham1.setBorderPainted(false);
        btnSanpham1.setContentAreaFilled(false);
        btnSanpham1.setDefaultCapable(false);
        btnSanpham1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSanpham1.setIconTextGap(25);
        btnSanpham1.setMaximumSize(new java.awt.Dimension(175, 20));
        btnSanpham1.setMinimumSize(new java.awt.Dimension(175, 20));
        btnSanpham1.setPreferredSize(new java.awt.Dimension(175, 20));
        btnSanpham1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanpham1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSanpham1Layout = new javax.swing.GroupLayout(pnlSanpham1);
        pnlSanpham1.setLayout(pnlSanpham1Layout);
        pnlSanpham1Layout.setHorizontalGroup(
            pnlSanpham1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSanpham1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnSanpham1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlSanpham1Layout.setVerticalGroup(
            pnlSanpham1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSanpham1Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(btnSanpham1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
        );

        pnlMenu.add(pnlSanpham1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 230, -1));

        pnlNhanvien.setBackground(new java.awt.Color(55, 38, 91));
        pnlNhanvien.setPreferredSize(new java.awt.Dimension(230, 47));

        btnNhanvien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNhanvien.setForeground(new java.awt.Color(255, 255, 255));
        btnNhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/officer.png"))); // NOI18N
        btnNhanvien.setText("Quản lý nhân viên");
        btnNhanvien.setBorder(null);
        btnNhanvien.setBorderPainted(false);
        btnNhanvien.setContentAreaFilled(false);
        btnNhanvien.setDefaultCapable(false);
        btnNhanvien.setIconTextGap(25);
        btnNhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanvienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNhanvienLayout = new javax.swing.GroupLayout(pnlNhanvien);
        pnlNhanvien.setLayout(pnlNhanvienLayout);
        pnlNhanvienLayout.setHorizontalGroup(
            pnlNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        pnlNhanvienLayout.setVerticalGroup(
            pnlNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNhanvienLayout.createSequentialGroup()
                .addComponent(btnNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlMenu.add(pnlNhanvien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 230, -1));

        getContentPane().add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 800));

        jPanel2.setBackground(new java.awt.Color(235, 235, 235));
        jPanel2.setMinimumSize(new java.awt.Dimension(990, 70));
        jPanel2.setPreferredSize(new java.awt.Dimension(1090, 70));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setDefaultCapable(false);
        jButton1.setFocusPainted(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setName(""); // NOI18N
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(55, 38, 91));
        jLabel1.setText("HỆ THỐNG BÁN HÀNG");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel1.setMaximumSize(new java.awt.Dimension(297, 24));
        jLabel1.setMinimumSize(new java.awt.Dimension(297, 24));
        jLabel1.setPreferredSize(new java.awt.Dimension(297, 24));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 23, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, -1));

        pnlContent.setBackground(new java.awt.Color(211, 211, 211));
        pnlContent.setMinimumSize(new java.awt.Dimension(1080, 710));
        pnlContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlContent.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 690));

        getContentPane().add(pnlContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 1070, 690));

        jPanel5.setBackground(new java.awt.Color(55, 38, 91));
        jPanel5.setAlignmentX(0.0F);
        jPanel5.setAlignmentY(0.0F);
        jPanel5.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel5.setMinimumSize(new java.awt.Dimension(1265, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(1136, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 760, 1300, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanphamActionPerformed
       OpenLoaiSP();
    }//GEN-LAST:event_btnSanphamActionPerformed

    private void btnNhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanvienActionPerformed
        // TODO add your handling code here:
        OpenNhanVien();
    }//GEN-LAST:event_btnNhanvienActionPerformed

    private void btnKhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachhangActionPerformed
        // TODO add your handling code here:
        OpenKhachHang();
    }//GEN-LAST:event_btnKhachhangActionPerformed

    private void btnThanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhtoanActionPerformed
        OpenHoaDon();
    }//GEN-LAST:event_btnThanhtoanActionPerformed

    private void btnthongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthongkeActionPerformed
        OpenThongKe();
    }//GEN-LAST:event_btnthongkeActionPerformed

    private void btnSanpham1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanpham1ActionPerformed
      OpenSanPham();
    }//GEN-LAST:event_btnSanpham1ActionPerformed

    private void btnAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountActionPerformed
        OpenDMK();
    }//GEN-LAST:event_btnAccountActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
      dangXuat();
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFormJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFormJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFormJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFormJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFormJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccount;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnKhachhang;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNhanvien;
    private javax.swing.JButton btnSanpham;
    private javax.swing.JButton btnSanpham1;
    private javax.swing.JButton btnSetting;
    private javax.swing.JButton btnThanhtoan;
    private javax.swing.JButton btnthongke;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblChucVu;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlKH;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlNhanvien;
    private javax.swing.JPanel pnlSanpham1;
    private javax.swing.JPanel pnlThanhtoan;
    private javax.swing.JPanel pnlTrangChu;
    private javax.swing.JPanel pnlsp;
    private javax.swing.JPanel pnlthongke;
    // End of variables declaration//GEN-END:variables
}
