/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import DungChung.ExportExcel;
import edu.QLCH.Dao.KhachHangDao;
import edu.QLCH.Dao.NhanVienDao;
import edu.QLCH.Entity.KhachHang;
import edu.QLCH.Entity.NhanVien;
import edu.QLCH.Helper.AuthHelper;
import edu.QLCH.Helper.DateHelper;
import edu.QLCH.Helper.MsgBoxHelper;
import edu.QLCH.Helper.ShareHelper;
import edu.QLCH.Helper.UtilityHelper;
import static java.awt.Color.pink;
import static java.awt.Color.white;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class QuanLyKhachHangJDialog extends javax.swing.JDialog {

    /**
     * Creates new form QuanLyKhachHang1JDialog
     */
    public QuanLyKhachHangJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }
        int row = 0; // Hàng được chọn hiện tại trên bảng
    KhachHangDao dao = new KhachHangDao();

    void init(){
            setLocationRelativeTo(null);
            setTitle("HỆ THỐNG QUẢN LÝ NHÂN VIÊN");
            fillTable();
            this.row = -1;
            this.updateStatus();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    void fillTable() {
       DefaultTableModel model = (DefaultTableModel) tblKIhachHang.getModel();
       model.setRowCount(0); // Xóa tất cả các hàng trên JTable
        try {
            List<KhachHang> list = dao.selectAll();
            for (KhachHang kh : list){
                Object[] row ={
                    kh.getMaKH(),
                    kh.getTenKH(),
                    kh.getDiaChi(),
                    kh.getNgaySinh(),
                    kh.getDienThoai(),
                    kh.getEmail(),
                    kh.getGhiChu(),
                };
                model.addRow(row);// Thêm một hàng vào JTable
            }
        } catch (Exception e) {
        e.printStackTrace();
        MsgBoxHelper.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }
    
    void setForm(KhachHang kh){
        txtMaKH.setText(kh.getMaKH());
        txtTenKH.setText(kh.getTenKH());
        txtDiaChi.setText(kh.getDiaChi());
        txtNgaySinh.setText(DateHelper.toString(kh.getNgaySinh(), "dd/MM/yyyy"));
        txtDienThoai.setText(kh.getDienThoai());
        txtEmail.setText(kh.getEmail());
//        txtGhiChu.setText(kh.getGhiChu());
        
    }   
     KhachHang getForm(){
         KhachHang kh = new KhachHang();
         kh.setMaKH(txtMaKH.getText());
         kh.setTenKH(txtTenKH.getText());
         kh.setDiaChi(txtDiaChi.getText());
         kh.setNgaySinh(DateHelper.toDate(txtNgaySinh.getText(), "dd/MM/yyyy"));
         kh.setDienThoai(txtDienThoai.getText());
         kh.setEmail(txtEmail.getText());
//         kh.setGhiChu(txtGhiChu.getText());
         return kh;
     }
    void clearForm(){
        KhachHang kh = new KhachHang();
        kh.setNgaySinh(new Date());
        this.setForm(kh);
        
        row = -1;
        updateStatus();
        
    }
    void edit(){
        try{
            String manv = (String) tblKIhachHang.getValueAt(this.row, 0);
            KhachHang model = dao.selectById(manv);
            if (model != null){
                setForm(model);
                updateStatus();
//                tabs.setSelectedIndex(0);
            }
        }catch (Exception e){
            MsgBoxHelper.alert(this, "Lỗi try vấn dữ liệu");
        }
//        String manv = (String) tblGridView.getValueAt(this.row, 0);
//        NhanVien nv = dao.selectById(manv);
//        this.setForm(nv);
//        tabs.setSelectedIndex(0);
//        this.updateStatus();
    }
      private void exportExcel() {
        new ExportExcel().exportExcel("DANH SÁCH BẢNG SẢN PHẨM", "SẢN PHẨM", tblKIhachHang, new int[]{2000, 5000, 5000, 6000, 5000,5000});
        JOptionPane.showMessageDialog(this, "Xuất file excel thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }
     void insert(){
        KhachHang model = getForm();
        try {
            dao.insert(model);
            fillTable();
            clearForm();
            MsgBoxHelper.alert(this, "Thêm mới thành công");
        } catch (Exception e) {
            e.printStackTrace();
            MsgBoxHelper.alert(this, "Thêm mới thất bại");
        }
    }
    void update(){
        KhachHang model = getForm();
        try {
            dao.update(model);
            fillTable();
            MsgBoxHelper.alert(this, "cập nhật thành công");
        } catch (Exception e) {
            e.printStackTrace();
            MsgBoxHelper.alert(this, "Cập nhật thất bại");
        }
    }
    void delete(){
         if(!AuthHelper.isManager()){
            MsgBoxHelper.alert(this, "Bạn không có quyền xóa người học!");
        }else{
            if(MsgBoxHelper.confirm(this, "Bạn có muốn xóa hay không")){
                String manh = txtMaKH.getText();
                try {
                    dao.delete(manh);
                    fillTable();
                    clearForm();
                    MsgBoxHelper.alert(this, "Xóa thành công");
                } catch (Exception e) {
                    MsgBoxHelper.alert(this, "Xóa thất bại");
                }
            }
        }
    }
    
    void first(){
        row = 0;
        edit();
    }    
    void prev(){
        if(row > 0){
            row--;
            edit();
        }
    }
    void next(){
        if(row < tblKIhachHang.getRowCount()-1){
            row ++;
            edit();
        }
    }
    void last(){
        row = tblKIhachHang.getRowCount()-1;
        edit();
    }
    
    void updateStatus(){
//        boolean edit = (this.row >= 0);
//        boolean first = (this.row == 0);
//        boolean last = this.row == (tblKIhachHang.getRowCount()-1);
//        // Trạng thái form
//        txtMaKH.setEditable(edit);
//        btnThem.setEnabled(edit);
//        btnCapNhat.setEnabled(edit);
//        btnXoa.setEnabled(edit);
//        //trạng thái điều hướng
//        btnFirst.setEnabled(edit && !first);//enable 4 nút này khi ở editable
//        btnPrev.setEnabled(edit && !first); //disable khi First, Prev khi ở bản ghi đầu (index = 0)
//        btnNext.setEnabled(edit && !last);  //disable khi Next, Last khi ở bản ghi cuối
//        btnLast.setEnabled(edit && !last);  //index = tblGridView.getRowCount() - 1
    }
    
    private void timKiem(){
        fillTable();
        clearForm();
        row = -1;
        updateStatus();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDienThoai = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKIhachHang = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabs.setBackground(new java.awt.Color(255, 255, 255));
        tabs.setToolTipText("");
        tabs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabsMousePressed(evt);
            }
        });
        tabs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(55, 38, 91));
        jLabel1.setText("Quản Lí Khách Hàng");
        tabs.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Tìm Kiếm");
        tabs.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, -1));
        tabs.add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 183, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Mã Khách Hàng");
        tabs.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));
        tabs.add(txtMaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 232, -1));
        tabs.add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 340, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Số Điện Thoại");
        tabs.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));
        tabs.add(txtDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 232, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Email");
        tabs.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        txtNgaySinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgaySinhActionPerformed(evt);
            }
        });
        tabs.add(txtNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 340, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Ngày Sinh");
        tabs.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, -1, -1));

        tblKIhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MaKH", "TenKH", "Địa Chỉ", "Ngày Sinh", "Điện Thoại", "Email"
            }
        ));
        tblKIhachHang.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tblKIhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblKIhachHangMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblKIhachHang);

        tabs.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 840, 290));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgButtonThem.png"))); // NOI18N
        btnThem.setBorder(null);
        btnThem.setBorderPainted(false);
        btnThem.setContentAreaFilled(false);
        btnThem.setDefaultCapable(false);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        tabs.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 120, -1));

        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgButtonCapNhat.png"))); // NOI18N
        btnCapNhat.setBorder(null);
        btnCapNhat.setBorderPainted(false);
        btnCapNhat.setContentAreaFilled(false);
        btnCapNhat.setDefaultCapable(false);
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });
        tabs.add(btnCapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 140, -1));

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgButtonXoa.png"))); // NOI18N
        btnXoa.setBorder(null);
        btnXoa.setBorderPainted(false);
        btnXoa.setContentAreaFilled(false);
        btnXoa.setDefaultCapable(false);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        tabs.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 120, -1));

        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgButtonMoi.png"))); // NOI18N
        btnMoi.setBorder(null);
        btnMoi.setBorderPainted(false);
        btnMoi.setContentAreaFilled(false);
        btnMoi.setDefaultCapable(false);
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });
        tabs.add(btnMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, -1, -1));

        btnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgDau.png"))); // NOI18N
        btnFirst.setBorder(null);
        btnFirst.setBorderPainted(false);
        btnFirst.setContentAreaFilled(false);
        btnFirst.setDefaultCapable(false);
        tabs.add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 640, 73, -1));

        btnPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgPre.png"))); // NOI18N
        btnPrev.setBorder(null);
        btnPrev.setBorderPainted(false);
        btnPrev.setContentAreaFilled(false);
        btnPrev.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPrev.setDefaultCapable(false);
        tabs.add(btnPrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 640, 73, -1));

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgNext.png"))); // NOI18N
        btnNext.setBorder(null);
        btnNext.setBorderPainted(false);
        btnNext.setContentAreaFilled(false);
        btnNext.setDefaultCapable(false);
        tabs.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 640, 73, -1));

        btnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgCuoi.png"))); // NOI18N
        btnLast.setBorder(null);
        btnLast.setBorderPainted(false);
        btnLast.setContentAreaFilled(false);
        btnLast.setDefaultCapable(false);
        tabs.add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 640, 73, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Địa Chỉ");
        tabs.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, -1));
        tabs.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 232, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Họ Tên");
        tabs.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, -1));
        tabs.add(txtTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 340, -1));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgButtonExcel.png"))); // NOI18N
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setDefaultCapable(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        tabs.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 640, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 1022, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public boolean checkTrungMa(JTextField txt) {
        txt.setBackground(white);
        if (dao.selectById(txt.getText()) == null) {
            return true;
        } else {
            txt.setBackground(pink);
            MsgBoxHelper.alert(this, txt.getName() + " đã bị tồn tại.");
            return false;
        }
    }
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (UtilityHelper.checkNullText(txtMaKH)
                && UtilityHelper.checkNullText(txtTenKH)
                && UtilityHelper.checkNullText(txtNgaySinh)
                && UtilityHelper.checkNullText(txtDienThoai)
                && UtilityHelper.checkNullText(txtEmail)
                && UtilityHelper.checkNullText(txtDiaChi)) {
            if (UtilityHelper.checkMaNH(txtMaKH)
                    && UtilityHelper.checkName(txtTenKH)
                    && UtilityHelper.checkDate(txtNgaySinh)
                    && UtilityHelper.checkSDT(txtDienThoai)
                    && UtilityHelper.checkEmail(txtEmail)) {
                if (checkTrungMa(txtMaKH)) {
                    insert();
                }
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void txtNgaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgaySinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgaySinhActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
      delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tabsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabsMousePressed
  // TODO add your handling code here:
    }//GEN-LAST:event_tabsMousePressed

    private void tblKIhachHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKIhachHangMousePressed
     if (evt.getClickCount() == 2) {
            this.row = tblKIhachHang.rowAtPoint(evt.getPoint());//lấy vị trí dòng được chọn
            edit();
            fillTable();
        }     
    }//GEN-LAST:event_tblKIhachHangMousePressed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        exportExcel();
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhachHangJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhachHangJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhachHangJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhachHangJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuanLyKhachHangJDialog dialog = new QuanLyKhachHangJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel tabs;
    private javax.swing.JTable tblKIhachHang;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtDienThoai;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
