/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import edu.QLCH.Dao.NhanVienDao;
import edu.QLCH.Entity.NhanVien;
import edu.QLCH.Helper.AuthHelper;
import edu.QLCH.Helper.MsgBoxHelper;
import edu.QLCH.Helper.ShareHelper;
import edu.QLCH.Helper.UtilityHelper;
import static java.awt.Color.pink;
import static java.awt.Color.white;
import java.util.List;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class QuanLyNhanVienJDialog extends javax.swing.JDialog {

    /**
     * Creates new form QuanLyNhanVien1JDialog
     */
    public QuanLyNhanVienJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }
      int row = 0; // Hàng được chọn hiện tại trên bảng
    NhanVienDao dao = new NhanVienDao();

    void init(){
            
            setLocationRelativeTo(null);
            setTitle("HỆ THỐNG QUẢN LÝ NHÂN VIÊN");
            fillTable();
            this.row = -1;
            this.updateStatus();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    void fillTable() {
       DefaultTableModel model = (DefaultTableModel) tblNhanvien.getModel();
       model.setRowCount(0); // Xóa tất cả các hàng trên JTable
        try {
            List<NhanVien> list = dao.selectAll();
            for (NhanVien nv : list){
                Object[] row ={
                    nv.getMaNV(),
                    nv.getHoTen(),
                    nv.getMatKhau(),
                    nv.isVaiTro()?"Trưởng phòng":"Nhân viên",
                    nv.isGioiTinh()?"Nữ":"Nam"
                };
                model.addRow(row);// Thêm một hàng vào JTable
            }
        } catch (Exception e) {
        MsgBoxHelper.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }
    
    void setForm(NhanVien nv){
        txtMaNV.setText(nv.getMaNV());
        txtHoTen.setText(nv.getHoTen());
        txtPassword.setText(nv.getMatKhau());
        rdoTruongPhong.setSelected(nv.isVaiTro());
        rdoNhanVien.setSelected(!nv.isVaiTro());
        rdbNam.setSelected(nv.isGioiTinh());
        rdbNu.setSelected(nv.isGioiTinh());
        
    }   
     NhanVien getForm(){
         NhanVien nv = new NhanVien();
         nv.setMaNV(txtMaNV.getText());
         nv.setHoTen(txtHoTen.getText());
         nv.setMatKhau(new String(txtPassword.getPassword()));
         nv.setVaiTro(rdoTruongPhong.isSelected());
         return nv;
     }
    void clearForm(){
        this.setForm(new NhanVien());
        row = -1;
        updateStatus();
    }
    void edit(){
        try{
            String manv = (String) tblNhanvien.getValueAt(this.row, 0);
            NhanVien model = dao.selectById(manv);
            if (model != null){
                setForm(model);
                updateStatus();
//                tabs.setSelectedIndex(0);
            }
        }catch (Exception e){
            MsgBoxHelper.alert(this, "Lỗi try vấn dữ liệu");
        }
//        String manv = (String) tblGridView.getValueAt(this.row, 0);
//        NhanVien nv = dao.selectById(manv);
//        this.setForm(nv);
//        tabs.setSelectedIndex(0);
//        this.updateStatus();
    }
    
    void insert(){
        NhanVien nv = getForm();
        String mk2 = new String(txtPassword.getPassword());
        if(mk2.equals(nv.getMatKhau())){
           try{        
               dao.insert(nv);
               this.fillTable();
               this.clearForm();
               
               MsgBoxHelper.alert(this, "Thêm mới thành công");
           }catch (Exception e){
               MsgBoxHelper.alert(this, "Thêm mới thất bại");
           }
        }else{
            MsgBoxHelper.alert(this, "Xác nhận mật khẩu không đúng");
        }
    }
    void update(){
        NhanVien nv = getForm();
        String mk2 = new String(txtPassword.getPassword());
        if(!mk2.equals(nv.getMatKhau())){
            MsgBoxHelper.alert(this, "Xác nhận mật khẩu không đúng!");
        }else{
            try {
                dao.update(nv);
                this.fillTable();
                MsgBoxHelper.alert(this, "Cập nhật thành công");
            } catch (Exception e) {
                MsgBoxHelper.alert(this, "Cập nhật thất bại");
            }
        }
    }
    void delete(){
         if (!AuthHelper.isManager()){
             MsgBoxHelper.alert(this, "Bạn không có quyền xóa nhân viên");
         }else{
             String manv = txtMaNV.getText();
             if (manv.equals(AuthHelper.user.getMaNV())){
                 MsgBoxHelper.alert(this, "Bạn không được xóa chính mình");
             }else if (MsgBoxHelper.confirm(this, "Bạn thực sự muốn xóa nhân viên này")){
                 try{
                     dao.delete(manv);
                     this.fillTable();
                     this.clearForm();
                     MsgBoxHelper.alert(this, "Xóa thành công");
                 }catch (Exception e){
                     MsgBoxHelper.alert(this, "Xóa Thất bại!");
                 }
             }
         }
    }
    
    void first(){
        row = 0;
        edit();
    }    
    void prev(){
        if(row > 0){
            row--;
            edit();
        }
    }
    void next(){
        if(row < tblNhanvien.getRowCount()-1){
            row ++;
            edit();
        }
    }
    void last(){
        row = tblNhanvien.getRowCount()-1;
        edit();
    }
    
    void updateStatus(){
        boolean edit = this.row >= 0;
        boolean first = this.row == 0;
        boolean last = this.row == tblNhanvien.getRowCount()-1;
        // Trạng thái form
        txtMaNV.setEditable(!edit);
        btnThem.setEnabled(!edit);
        btnSua.setEnabled(edit);
        btnXoa.setEnabled(edit);
        //trạng thái điều hướng
        btnFirst.setEnabled(edit && !first);//enable 4 nút này khi ở editable
        btnPre.setEnabled(edit && !first); //disable khi First, Prev khi ở bản ghi đầu (index = 0)
        btnNext.setEnabled(edit && !last);  //disable khi Next, Last khi ở bản ghi cuối
        btnLast.setEnabled(edit && !last);  //index = tblGridView.getRowCount() - 1
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        rdoTruongPhong = new javax.swing.JRadioButton();
        rdoNhanVien = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rdbNam = new javax.swing.JRadioButton();
        rdbNu = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lblHinh = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        bntMoi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanvien = new javax.swing.JTable();
        btnPre = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        lblSTT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabs.setBackground(new java.awt.Color(255, 255, 255));
        tabs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(55, 38, 91));
        jLabel1.setText("QUẢN LÝ NHÂN VIÊN");
        tabs.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 11, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(55, 38, 91));
        jLabel3.setText("Mã nhân viên");
        tabs.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        txtMaNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaNV.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtMaNV.setOpaque(false);
        txtMaNV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMaNVKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMaNVKeyTyped(evt);
            }
        });
        tabs.add(txtMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 220, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(55, 38, 91));
        jLabel6.setText("Mật khẩu");
        tabs.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPassword.setBorder(null);
        txtPassword.setOpaque(false);
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordKeyTyped(evt);
            }
        });
        tabs.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 220, -1));
        tabs.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 220, 10));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(55, 38, 91));
        jLabel7.setText("Vai trò");
        tabs.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, -1));

        rdoTruongPhong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdoTruongPhong.setText("Trưởng phòng");
        rdoTruongPhong.setBorder(null);
        rdoTruongPhong.setOpaque(false);
        tabs.add(rdoTruongPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, -1));

        rdoNhanVien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdoNhanVien.setText("Nhân viên");
        rdoNhanVien.setBorder(null);
        rdoNhanVien.setOpaque(false);
        rdoNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNhanVienActionPerformed(evt);
            }
        });
        tabs.add(rdoNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(55, 38, 91));
        jLabel2.setText("Tìm kiếm");
        tabs.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, -1, -1));

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTimKiem.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtTimKiem.setOpaque(false);
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });
        tabs.add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 180, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(55, 38, 91));
        jLabel5.setText("Giới tính");
        tabs.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, -1, -1));

        rdbNam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdbNam.setText("Nam");
        rdbNam.setBorder(null);
        rdbNam.setOpaque(false);
        tabs.add(rdbNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 90, -1, -1));

        rdbNu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdbNu.setText("Nữ");
        rdbNu.setBorder(null);
        rdbNu.setOpaque(false);
        tabs.add(rdbNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 90, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(55, 38, 91));
        jLabel9.setText("Họ tên");
        tabs.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        txtHoTen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHoTen.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtHoTen.setOpaque(false);
        tabs.add(txtHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 220, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(55, 38, 91));
        jLabel11.setText("Hình");
        tabs.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, -1, -1));

        lblHinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinh.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblHinh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblHinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinhMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHinhMouseEntered(evt);
            }
        });
        tabs.add(lblHinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, 110, 140));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgButtonThem.png"))); // NOI18N
        btnThem.setBorder(null);
        btnThem.setBorderPainted(false);
        btnThem.setContentAreaFilled(false);
        btnThem.setDefaultCapable(false);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        tabs.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgButtonCapNhat.png"))); // NOI18N
        btnSua.setBorder(null);
        btnSua.setBorderPainted(false);
        btnSua.setContentAreaFilled(false);
        btnSua.setDefaultCapable(false);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        tabs.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgButtonXoa.png"))); // NOI18N
        btnXoa.setBorder(null);
        btnXoa.setBorderPainted(false);
        btnXoa.setContentAreaFilled(false);
        btnXoa.setDefaultCapable(false);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        tabs.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, -1));

        bntMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgButtonMoi.png"))); // NOI18N
        bntMoi.setBorder(null);
        bntMoi.setBorderPainted(false);
        bntMoi.setContentAreaFilled(false);
        bntMoi.setDefaultCapable(false);
        bntMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMoiActionPerformed(evt);
            }
        });
        tabs.add(bntMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, -1, -1));

        tblNhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MaNV", "Họ Tên", "Mật Khẩu", "Giới Tính", "Vai Trò"
            }
        ));
        tblNhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblNhanvienMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhanvien);

        tabs.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 950, 160));

        btnPre.setText("<<");
        tabs.add(btnPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, -1, -1));

        btnFirst.setText("|<");
        tabs.add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, -1, -1));

        btnLast.setText(">|");
        tabs.add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, -1, -1));

        btnNext.setText(">>");
        tabs.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, -1, -1));

        lblSTT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSTT.setForeground(new java.awt.Color(55, 38, 91));
        lblSTT.setText("0");
        tabs.add(lblSTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 550, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 1038, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaNVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaNVKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNVKeyReleased

    private void txtMaNVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaNVKeyTyped

    }//GEN-LAST:event_txtMaNVKeyTyped

    private void txtPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyTyped

    }//GEN-LAST:event_txtPasswordKeyTyped

    private void rdoNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNhanVienActionPerformed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased

    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void tblNhanvienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanvienMousePressed
 if (evt.getClickCount() == 2) {
            this.row = tblNhanvien.rowAtPoint(evt.getPoint());//lấy vị trí dòng được chọn
            edit();
            fillTable();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tblNhanvienMousePressed

     public boolean checkTrungMa(JTextField txt) {
        txt.setBackground(white);
        if (dao.selectById(txt.getText()) == null) {
            return true;
        } else {
            txt.setBackground(pink);
            MsgBoxHelper.alert(this, txt.getName() + " đã bị tồn tại.");
            return false;
        }
    }
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (UtilityHelper.checkNullText(txtMaNV)
                && UtilityHelper.checkNullText(txtHoTen)
                && UtilityHelper.checkNullText(txtPassword)
                ) {
            if (UtilityHelper.checkMaNH(txtMaNV)
                    && UtilityHelper.checkName(txtHoTen)
                   ) {
                if (checkTrungMa(txtMaNV)) {
                    insert();
                }
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void bntMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMoiActionPerformed
        clearForm();
    }//GEN-LAST:event_bntMoiActionPerformed

    private void lblHinhMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhMouseEntered

    }//GEN-LAST:event_lblHinhMouseEntered

    private void lblHinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhMouseClicked

    }//GEN-LAST:event_lblHinhMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVienJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVienJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVienJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVienJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuanLyNhanVienJDialog dialog = new QuanLyNhanVienJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntMoi;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPre;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JLabel lblSTT;
    private javax.swing.JRadioButton rdbNam;
    private javax.swing.JRadioButton rdbNu;
    private javax.swing.JRadioButton rdoNhanVien;
    private javax.swing.JRadioButton rdoTruongPhong;
    private javax.swing.JPanel tabs;
    private javax.swing.JTable tblNhanvien;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
